### PR TITLE
initial commit 

### PR DESCRIPTION
**Pull request by AzukaUgbekile**
Appbar and menu item components added

### CODE REVIEW

**Comment by BorisLaboratory** [comment]
It looks like MenuItem component has a comment that is not necessary on line 21

**Comment by BorisLaboratory** [comment]
The 1201 zIndex of NavBar seems high

**Comment by BorisLaboratory** [comment]
The zIndex is affecting the presentation of other associates user stories 
You may need to do a git pull and update as follows , eg :

ie AppBar xIndex=-1
Drawer xIndex=1
Home menu Button zIndex=2

**Comment by AzukaUgbekile** [comment]
Ok. Will do that later in the day

**Comment by AzukaUgbekile** [comment]
Witness values the drawer is overlapping the navigation bar

**Comment by AzukaUgbekile** [comment]
Chris, changes made. Am not the one handling the main menu buttons

**Pull request closed without merging**
